mod protocol_schema;

use std::collections::{BTreeMap, BTreeSet};
use std::error::Error;
use std::fs;
use std::path::Path;

use heck::ToSnakeCase;
use linkrpc::prelude::{GenerateRustOptions, generate_rust_interface};
use linkrpc::schema::Components;
use linkrpc::schema::codegen::{GenerateRustBinding, InterfaceAddress, generate_rust_components};

const HEADER: &str = "// @generated by npm run generate:cdp. DO NOT EDIT.\n";

fn main() -> Result<(), Box<dyn Error>> {
    let arguments = std::env::args().skip(1).collect::<Vec<_>>();
    let check = match arguments.as_slice() {
        [] => false,
        [argument] if argument == "--check" => true,
        _ => return Err("usage: generate-cdp [--check]".into()),
    };
    let repository = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
    let protocol = repository.join("node_modules/devtools-protocol/json");
    let domains = protocol_schema::import_cdp_domains(
        &fs::read_to_string(protocol.join("browser_protocol.json"))?,
        &fs::read_to_string(protocol.join("js_protocol.json"))?,
    )?;
    let mut schemas = BTreeMap::new();
    for domain in &domains {
        for (name, schema) in domain
            .interface
            .components
            .as_ref()
            .and_then(|components| components.schemas.as_ref())
            .into_iter()
            .flatten()
        {
            if let Some(previous) = schemas.insert(name.clone(), schema.clone())
                && previous != *schema
            {
                return Err(format!("conflicting shared CDP component: {name}").into());
            }
        }
    }
    let shared = generate_rust_components(
        &Components {
            schemas: Some(schemas),
        },
        &GenerateRustOptions::default(),
    );
    let external_components: BTreeMap<_, _> = shared
        .names
        .iter()
        .map(|(wire, name)| (wire.clone(), format!("super::types::{name}")))
        .collect();
    let mut unsupported = shared.unsupported;
    let mut files = BTreeMap::from([("types.rs".to_owned(), shared.code)]);
    let mut modules = String::from("mod types;\npub use types::*;\n");
    let mut client = String::from(
        "#[derive(Clone)]\npub struct CdpClient<C> { caller: C }\n\
         impl<C: linkrpc::prelude::RpcCall + Clone> CdpClient<C> {\n\
         pub fn root(caller: C) -> Self { Self { caller } }\n",
    );
    let mut catalog = String::from(
        "pub fn interfaces() -> Vec<(String, linkrpc::prelude::InterfaceDefinition)> {\nvec![\n",
    );
    for domain in &domains {
        let module = domain.name.to_snake_case();
        let client_name = format!("{}Client", domain.name);
        let generated = generate_rust_interface(
            &domain.interface,
            &GenerateRustOptions {
                client_name: Some(client_name.clone()),
                generate_server: true,
                default_server_methods: true,
                external_components: external_components.clone(),
                method_type_prefix: Some(domain.name.clone()),
                bindings: vec![GenerateRustBinding {
                    name: "DOMAIN".into(),
                    address: InterfaceAddress::Bare(domain.prefix.clone()),
                }],
                ..GenerateRustOptions::default()
            },
        );
        unsupported.extend(generated.unsupported);
        if files
            .insert(format!("{module}.rs"), generated.code)
            .is_some()
        {
            return Err(format!("duplicate CDP Rust module: {module}").into());
        }
        modules.push_str(&format!("pub mod {module};\n"));
        client.push_str(&format!(
            "pub fn {module}(&self) -> {module}::{client_name}<C> {{ {module}::DOMAIN.client(self.caller.clone()) }}\n",
        ));
        catalog.push_str(&format!(
            "({module}::DOMAIN.prefix(), {module}::DOMAIN.interface()),\n",
        ));
    }
    verify_expected_fallbacks(&unsupported)?;
    modules.push_str(&client);
    modules.push_str("}\n");
    modules.push_str(&catalog);
    modules.push_str("]\n}\n");
    files.insert("mod.rs".into(), modules);
    write_outputs(
        &repository.join("crates/cdp-protocol/src/generated"),
        files,
        check,
    )?;
    Ok(())
}

fn write_outputs(
    directory: &Path,
    files: BTreeMap<String, String>,
    check: bool,
) -> Result<(), Box<dyn Error>> {
    if directory.exists() {
        for entry in fs::read_dir(directory)? {
            let entry = entry?;
            if !files.contains_key(&entry.file_name().to_string_lossy().into_owned()) {
                return Err(
                    format!("obsolete generated output: {}", entry.path().display()).into(),
                );
            }
        }
    }
    if !check {
        fs::create_dir_all(directory)?;
    }
    for (name, code) in files {
        let output = directory.join(name);
        let code = format!("{HEADER}{code}");
        if check {
            match fs::read_to_string(&output) {
                Ok(current) if current == code => {}
                Ok(_) => {
                    return Err(
                        format!("{} is stale; run npm run generate:cdp", output.display()).into(),
                    );
                }
                Err(error) => {
                    return Err(format!("cannot check {}: {error}", output.display()).into());
                }
            }
        } else {
            fs::write(output, code)?;
        }
    }
    Ok(())
}

fn verify_expected_fallbacks(unsupported: &[String]) -> Result<(), Box<dyn Error>> {
    let expected = BTreeSet::from([
        "AccessibilityAxvalueValue",
        "DomShapeOutsideInfoMarginShapeItem",
        "DomShapeOutsideInfoShapeItem",
        "RuntimeCallArgumentValue",
        "RuntimeDeepSerializedValueValue",
        "RuntimeRemoteObjectValue",
        "WebMcpToolRespondedParamsOutput",
    ]);
    let actual = unsupported
        .iter()
        .filter_map(|message| {
            message
                .strip_prefix("component `")
                .and_then(|message| message.split_once('`'))
                .map(|(name, _)| name)
        })
        .collect::<BTreeSet<_>>();
    if actual != expected || actual.len() != unsupported.len() {
        return Err(format!(
            "unexpected CDP Rust generation fallbacks:\n{}",
            unsupported.join("\n")
        )
        .into());
    }
    Ok(())
}
