import assert from "node:assert/strict";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";

export const repositoryRoot = resolve(import.meta.dirname, "../..");
export const snapshotPath = resolve(repositoryRoot, "tests/readme/recording.json");
export const readmePath = resolve(repositoryRoot, "README.md");
const documents = [
	["docs/readme.template.md", "README.md"],
	["docs/walkthroughs/vscode.template.md", "docs/walkthroughs/vscode.md"],
	["docs/walkthroughs/website.template.md", "docs/walkthroughs/website.md"],
	["docs/walkthroughs/node.template.md", "docs/walkthroughs/node.md"],
];

export function normalize(text, replacements, { argument = false } = {}) {
	let result = text.replaceAll("\r\n", "\n")
		.replaceAll(" - Visual Studio Code [Administrator]", " - Visual Studio Code");
	for (const [value, name] of [...replacements].sort((a, b) => b[0].length - a[0].length)) {
		assert.ok(value.length > 0, "Cannot normalize an empty identity");
		if (/^\d+$/.test(value)) {
			if (argument && result === value) result = `$${name}`;
			else result = result.replace(
				new RegExp(`(p:|w:|process:|Process |Configuration: process |process-tree-|process tree |PID )${value}(?!\\d)`, "g"),
				(_match, prefix) => `${prefix}$${name}`,
			);
		} else {
			result = result.replaceAll(value, `$${name}`);
		}
	}
	return result.trimEnd();
}

export function formatCommand(args) {
	return "dbgjs " + args.map((arg) =>
		/^[a-zA-Z0-9_./:=,#-]+$/.test(arg.replace(/\$[A-Z][A-Z_0-9]*/g, "placeholder")) ? arg
			: /^\$[A-Z_]+\\[\w.-]+$/.test(arg) ? `"${arg}"`
			: `'${arg.replaceAll("'", "''")}'`,
	).join(" ");
}

function renderSteps(steps) {
	const fence = "````";
	const transcripts = [];
	const details = [];
	for (const step of steps) {
		const allLines = step.output.split("\n").map((line) => line.trimEnd());
		const mappingDiagnostics = step.foldMappingDiagnostics
			? allLines.filter((line) => line.startsWith("Mapping "))
			: [];
		const lines = step.foldMappingDiagnostics
			? allLines.filter((line) => !line.startsWith("Mapping "))
			: allLines;
		const excerpt = step.maxOutputLines && lines.length > step.maxOutputLines
			? lines.slice(0, step.maxOutputLines).join("\n") + `\n... (${lines.length - step.maxOutputLines} more lines; full output in the recording)`
			: lines.join("\n");
		transcripts.push(`$ ${formatCommand(step.args)}${excerpt ? `\n${excerpt}` : ""}`);
		if (mappingDiagnostics.length) {
			details.push(`<details><summary>${mappingDiagnostics.length} source-map diagnostics</summary>\n\n${fence}text\n${mappingDiagnostics.join("\n")}\n${fence}\n\n</details>`);
		}
		if (step.stderr) {
			details.push(`<details><summary>CLI stderr</summary>\n\n${fence}text\n${step.stderr}\n${fence}\n\n</details>`);
		}
	}
	return [`${fence}console\n${transcripts.join("\n\n")}\n${fence}`, ...details].join("\n\n");
}

export async function renderDocuments(recording) {
	const used = new Set();
	const byId = new Map(recording.steps.map((step) => {
		assert.match(step.id, /^[a-z-]+$/, "Recorded commands need stable IDs.");
		assert.ok(step.maxOutputLines === undefined || (Number.isSafeInteger(step.maxOutputLines) && step.maxOutputLines > 0));
		return [step.id, step];
	}));
	assert.equal(byId.size, recording.steps.length, "Recording contains duplicate command IDs.");
	const rendered = new Map();
	for (const [templatePath, outputPath] of documents) {
		const template = (await readFile(resolve(repositoryRoot, templatePath), "utf8")).replaceAll("\r\n", "\n");
		const text = template.replaceAll("{{vscode-version}}", recording.vscodeVersion)
			.replace(/\{\{example:([a-z,-]+)\}\}/g, (_match, ids) => {
				const steps = ids.split(",").map((id) => {
					used.add(id);
					assert.ok(byId.has(id), `No recorded command ${id} for ${outputPath}`);
					return byId.get(id);
				});
				return renderSteps(steps);
			});
		assert.doesNotMatch(text, /\{\{/, `Unresolved template marker in ${outputPath}`);
		rendered.set(outputPath, "<!-- Generated by npm run generate:readme. Do not edit command/output blocks. -->\n\n" + text);
	}
	for (const step of recording.steps) assert.ok(used.has(step.id), `Unrendered recorded command ${step.id}`);
	return rendered;
}

export async function checkGeneratedDocs() {
	const recording = JSON.parse(await readFile(snapshotPath, "utf8"));
	for (const [path, rendered] of await renderDocuments(recording)) {
		assert.equal((await readFile(resolve(repositoryRoot, path), "utf8")).replaceAll("\r\n", "\n"), rendered,
			`${path} differs from the CLI recording. Run npm run generate:readme.`);
	}
	return recording;
}

export function compareRecordings(actual, expected) {
	assert.equal(actual.vscodeVersion, expected.vscodeVersion);
	assert.equal(actual.steps.length, expected.steps.length, "README walkthrough commands changed; regenerate.");
	for (let index = 0; index < actual.steps.length; index++) {
		const step = actual.steps[index];
		const old = expected.steps[index];
		assert.deepEqual(
			{ id: step.id, args: step.args, comparison: step.comparison, maxOutputLines: step.maxOutputLines, foldMappingDiagnostics: step.foldMappingDiagnostics },
			{ id: old.id, args: old.args, comparison: old.comparison, maxOutputLines: old.maxOutputLines, foldMappingDiagnostics: old.foldMappingDiagnostics },
			`README command ${index + 1} changed; regenerate.`,
		);
		if (step.comparison === "exact") {
			assert.equal(step.output, old.output, `README output changed: ${formatCommand(step.args)}`);
			assert.equal(step.stderr, old.stderr, `README stderr changed: ${formatCommand(step.args)}`);
		} else if (step.comparison === "excerpt") {
			assert.ok(Number.isSafeInteger(step.maxOutputLines) && step.maxOutputLines > 0,
				"Excerpt comparison needs an explicit line bound.");
			assert.equal(
				step.output.split("\n").slice(0, step.maxOutputLines).join("\n"),
				old.output.split("\n").slice(0, old.maxOutputLines).join("\n"),
				`README source excerpt changed: ${formatCommand(step.args)}`,
			);
		} else {
			assert.equal(step.comparison, "live", "Unknown comparison policy");
		}
	}
}

export async function saveReadme(recording) {
	const rendered = await renderDocuments(recording);
	await writeFile(snapshotPath, JSON.stringify(recording, null, 2) + "\n");
	for (const [path, text] of rendered) await writeFile(resolve(repositoryRoot, path), text);
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
	const recording = JSON.parse(await readFile(snapshotPath, "utf8"));
	for (const [path, text] of await renderDocuments(recording)) {
		await writeFile(resolve(repositoryRoot, path), text);
	}
	console.log("Rendered README and walkthroughs from the recorded CLI run.");
}
